name: qr_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  pretty_qr_code: ^3.3.0
  mobile_scanner: ^6.0.7
  sqflite: ^2.4.2
dev_dependencies:
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/